export default {specific_film_html, films_html, specific_genre_html, genres_html, specific_actor_html, actors_html, index_html }

function specific_film_html(film){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>${film.title}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>${film.title}</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

            </div>

            <p class="w3-margin w3-padding">Estreia: <b>${film.year}</b></p>

            <div class="flex-box flex-center">
                <header class="w3-container w3-blue-grey w3-center w3-margin">
                    <p><b>Géneros</b></p>
                </header>

                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    if(film.film_genres != ''){
        film.film_genres.forEach(g => {
            final_html += `
            <li>
                <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/generos/${g}">${g}</a>
                </div>
            </li>
            `
        })
    }


    
    final_html += `
    </ul>

    <header class="w3-container w3-blue-grey w3-center w3-margin">
    
    <p><b>Atores</b></p>
    
    </header>
    
    <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    if(film.cast != ''){
        film.cast.forEach(a => {
            final_html += `
            <li>
                <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/atores/${a}">${a}</a>
                </div>
            </li>
            `
        })
    }

    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by FilmApp::EngWeb2024::A100695 [<a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

function films_html(films){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Filmes</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Filmes</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

            </div>

            <div class="flex-box flex-center">
                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    films.forEach(f => {
        final_html += `
        <li>
            <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                <a class="w3-center remove-text-decoration w3-hover-blue" href="/filmes/${f.id}">${f.title}</a>
            </div>
        </li>
        `
    })
                
    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by FilmApp::EngWeb2024::A100695 [<a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

function specific_genre_html(genre){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Género: ${genre.id}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Género: ${genre.id}</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

            </div>

            <div class="flex-box flex-center">
                <header class="w3-container w3-blue-grey w3-center w3-margin">
                    <p><b>Filmes</b></p>
                </header>

                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    genre.films.forEach(f => {
        final_html += `
        <li>
            <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                <a class="w3-center remove-text-decoration w3-hover-blue" href="/filmes/${f.id}">${f.title}</a>
            </div>
        </li>
        `
    })
                
    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by FilmApp::EngWeb2024::A100695 [<a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

function genres_html(genres){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Géneros</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Géneros</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

            </div>

            <div class="flex-box flex-center">
                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    genres.forEach(g => {
        final_html += `
        <li>
            <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                <a class="w3-center remove-text-decoration w3-hover-blue" href="/generos/${g.id}">${g.id}</a>
            </div>
        </li>
        `
    })
                
    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by FilmApp::EngWeb2024::A100695 [<a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

function specific_actor_html(actor){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>${actor.id}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>${actor.id}</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

            </div>

            <div class="flex-box flex-center">
                <header class="w3-container w3-blue-grey w3-center w3-margin">
                    <p><b>Filmes</b></p>
                </header>

                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    actor.films.forEach(f => {
        final_html += `
        <li>
            <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                <a class="w3-center remove-text-decoration w3-hover-blue" href="/filmes/${f.id}">${f.title}</a>
            </div>
        </li>
        `
    })
                
    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by FilmApp::EngWeb2024::A100695 [<a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

function actors_html(actors){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Atores</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Atores</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

            </div>

            <div class="flex-box flex-center">
                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    actors.forEach(a => {
        final_html += `
        <li>
            <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                <a class="w3-center remove-text-decoration w3-hover-blue" href="/atores/${a.id}">${a.id}</a>
            </div>
        </li>
        `
    })
                
    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by FilmApp::EngWeb2024::A100695 [<a class="w3-center remove-text-decoration w3-hover-blue" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

function index_html(){
    let final_html = `
        
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Filmes</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="style.css">
        <link rel="stylesheet" href="w3.css">
    </head>

    <body class="w3-light-grey">

            <header class="w3-container w3-blue-grey w3-center">
                <h3>Filmes</h3>
            </header>

            <div class="flex-box flex-center">
                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
                    <li>
                        <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                            <a class="w3-center remove-text-decoration w3-hover-blue" href="/filmes">Filmes</a>
                        </div>
                    </li>
                    <li>
                        <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                            <a class="w3-center remove-text-decoration w3-hover-blue" href="/atores">Atores</a>
                        </div>  
                    </li>
                    <li>
                        <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                            <a class="w3-center remove-text-decoration w3-hover-blue" href="/generos">Géneros</a>
                        </div>
                    </li>
                </ul>
            </div>

            <footer class="w3-container w3-blue-grey">
                <h5>Generated by FilmApp::EngWeb2024::A100695</h5>
            </footer>
    </body>

    </html>
    `

    return final_html
}