function mainPage (){
    return `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Compositores</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="favicon.png">
        <link rel="stylesheet" href="style.css">
        <link rel="stylesheet" href="w3.css">
    </head>

    <body class="w3-light-grey">

            <header class="w3-container w3-blue-grey w3-center">
                <h3>Compositores</h3>
            </header>

            <div class="flex-box flex-center">
                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
                    <li>
                        <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                            <a class="w3-center" href="/compositores">Compositores</a>
                        </div>
                    </li>
                    <li>
                        <div class="w3-light-blue w3-margin w3-padding w3-container w3-card-4 w3-center">
                            <a class="w3-center" href="/periodos">Periodos</a>
                        </div>  
                    </li>
                </ul>
            </div>

            <footer class="w3-container w3-blue-grey">
                <h5>Generated by CompositoresApp::EngWeb2024::A100695</h5>
            </footer>
    </body>

    </html>
    `
}

exports.mainPage = mainPage

function composerListPage(composerList){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Compositores</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center" href="/">Voltar</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Compositores</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <a class="w3-button w3-round w3-grey w3-margin w3-padding w3-center" href="/compositores/add">+</a>
            </div>

            </div>

            <div class="flex-box flex-center">
                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    composerList.forEach(c => {
        final_html += `
        <li>
            <div class="w3-light-blue w3-margin w3-padding w3-card-4 flex-box space-between">
                <a class="w3-center" href="/compositores/${c.id}">${c.nome}</a>
                <div>
                    [<a class="w3-center" href="/compositores/edit/${c.id}">Edit</a>]
                    [<a class="w3-center" href="/compositores/delete/${c.id}">Delete</a>]
                </div>
            </div>
        </li>
        `
    })
                
    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerListPage = composerListPage

function composerPage(composer){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>${composer.nome}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center" href="/compositores">Voltar</a>
                </div>
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>${composer.nome}</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <p><b>Data de Nascimento</b>: ${composer.dataNasc}</p>
            <p><b>Data de Óbito</b>: ${composer.dataObito}</p>
            <p><b>Período</b>: <a href="/periodos/${composer.periodo}">${composer.periodo}</a></p>

            <h4><b>Biografia</b></h4>

            <p>${composer.bio}</p>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerPage = composerPage

function composerEditPage(composer){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Editar Compositor</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Editar Compositor</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/compositores/edit/${composer.id}" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${composer.id}" pattern="C[0-9]+"/>
                    <br/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${composer.nome}"/>
                    <br/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc" value="${composer.dataNasc}"/>
                    <br/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito" value="${composer.dataObito}"/>
                    <br/>
                    <label>Período</label>
                    <input class="w3-input w3-round" type="text" name="periodo" value="${composer.periodo}"/>
                    <br/>
                    <div class="flex-box flex-column">
                        <label>Biografia</label>
                        <textarea id="biografia" name="bio" rows="10" cols="50">${composer.bio}</textarea>
                    <div>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/compositores">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerEditPage = composerEditPage

function composerFailedEditPage(composer){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Editar Compositor</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Editar Compositor</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <div class="w3-panel w3-red w3-margin w3-padding">
            <h3>Edição revertida!</h3>
            <p>O período indicado tem de existir na base de dados.</p>
        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/compositores/edit/${composer.id}" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${composer.id}" pattern="C[0-9]+"/>
                    <br/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${composer.nome}"/>
                    <br/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc" value="${composer.dataNasc}"/>
                    <br/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito" value="${composer.dataObito}"/>
                    <br/>
                    <label>Período</label>
                    <input class="w3-input w3-round" type="text" name="periodo" value="${composer.periodo}"/>
                    <br/>
                    <div class="flex-box flex-column">
                        <label>Biografia</label>
                        <textarea id="biografia" name="bio" rows="10" cols="50">${composer.bio}</textarea>
                    <div>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/compositores">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerFailedEditPage = composerFailedEditPage

function composerAddPage(){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Adicionar Compositor</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Adicionar Compositor</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/compositores/add" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" pattern="C[0-9]+"/>
                    <br/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome"/>
                    <br/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc"/>
                    <br/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito"/>
                    <br/>
                    <label>Período</label>
                    <input class="w3-input w3-round" type="text" name="periodo"/>
                    <br/>
                    <div class="flex-box flex-column">
                        <label>Biografia</label>
                        <textarea id="biografia" name="bio" rows="10" cols="50"></textarea>
                    <div>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/compositores">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerAddPage = composerAddPage

function composerEmptyAddPage(composer){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Adicionar Compositor</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Adicionar Compositor</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <div class="w3-panel w3-yellow w3-margin w3-padding">
            <h3>Adição impedida!</h3>
            <p>Nenhum pode permanecer em branco.</p>
        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/compositores/add" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${composer.id}" pattern="C[0-9]+"/>
                    <br/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${composer.nome}"/>
                    <br/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc" value="${composer.dataNasc}"/>
                    <br/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito" value="${composer.dataObito}"/>
                    <br/>
                    <label>Período</label>
                    <input class="w3-input w3-round" type="text" name="periodo" value="${composer.periodo}"/>
                    <br/>
                    <div class="flex-box flex-column">
                        <label>Biografia</label>
                        <textarea id="biografia" name="bio" rows="10" cols="50">${composer.bio}</textarea>
                    <div>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/compositores">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerEmptyAddPage = composerEmptyAddPage

function composerFailedAddPeriodPage(composer){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Adicionar Compositor</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Adicionar Compositor</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <div class="w3-panel w3-yellow w3-margin w3-padding">
            <h3>Adição impedida!</h3>
            <p>O periodo indicado precisa estar registado na base de dados.</p>
        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/compositores/add" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${composer.id}" pattern="C[0-9]+"/>
                    <br/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${composer.nome}"/>
                    <br/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc" value="${composer.dataNasc}"/>
                    <br/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito" value="${composer.dataObito}"/>
                    <br/>
                    <label>Período</label>
                    <input class="w3-input w3-round" type="text" name="periodo" value="${composer.periodo}"/>
                    <br/>
                    <div class="flex-box flex-column">
                        <label>Biografia</label>
                        <textarea id="biografia" name="bio" rows="10" cols="50">${composer.bio}</textarea>
                    <div>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/compositores">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerFailedAddPeriodPage = composerFailedAddPeriodPage

function composerFailedAddIdPage(composer){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Formulário do Compositor</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Formulário do Compositor</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <div class="w3-panel w3-yellow w3-margin w3-padding">
            <h3>Adição impedida!</h3>
            <p>O identificador do compositor precisa ser único.</p>
        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/compositores/add" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${composer.id}" pattern="C[0-9]+"/>
                    <br/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${composer.nome}"/>
                    <br/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc" value="${composer.dataNasc}"/>
                    <br/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito" value="${composer.dataObito}"/>
                    <br/>
                    <label>Período</label>
                    <input class="w3-input w3-round" type="text" name="periodo" value="${composer.periodo}"/>
                    <br/>
                    <div class="flex-box flex-column">
                        <label>Biografia</label>
                        <textarea id="biografia" name="bio" rows="10" cols="50">${composer.bio}</textarea>
                    <div>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/compositores">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerFailedAddIdPage = composerFailedAddIdPage

function composerDeletePage(composer){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Compositor apagado</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Compositor apagado</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <div class="w3-panel w3-green">
                <h3>Compositor apagado!</h3>
                <p>O compositor ${composer.nome} (${composer.id}) foi apagado com sucesso.</p>
            </div>
            <a class="w3-button w3-round w3-blue-grey" href="/compositores">Ok</a>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.composerDeletePage = composerDeletePage

function periodListPage(periodList){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Períodos</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">

            <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center" href="/">Voltar</a>
                </div>
            </div>
            
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Períodos</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <a class="w3-button w3-round w3-grey w3-margin w3-padding w3-center" href="/periodos/add">+</a>
            </div>

            </div>

            <div class="flex-box flex-center">
                <ul class="no-padding-inline-start no-mark-list w3-margin flex-box flex-column space-evenly" style="width:50%">
    `

    periodList.forEach(p => {
        final_html += `
        <li>
            <div class="w3-light-blue w3-margin w3-padding w3-card-4 flex-box space-between">
                <a class="w3-center" href="/periodos/${p.id}">${p.id}</a>
                <div>
                    [<a class="w3-center" href="/periodos/edit/${p.id}">Edit</a>]
                    ${p.compositores.length == 0 ? `[<a class="w3-center" href="/periodos/delete/${p.id}">Delete</a>]` : ""}
                </div>
            </div>
        </li>
        `
    })
                
    final_html += `
        </ul>
        </div>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodListPage = periodListPage

function periodPage(period){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>${period.id}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
                <div class="flex-box flex-center flex-column">
                    <a class="w3-center" href="/periodos">Voltar</a>
                </div>
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>${period.id}</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <div class="w3-container w3-center">
                <p><b>Início:</b> ${period.start}</p>
                <p><b>Fim:</b> ${period.end}</p>
            </div>
            <div class="flex-box flex-center">
                <header class="w3-container w3-blue-grey w3-center w3-margin">
                    <p><b>Compositores</b></p>
                </header>
    `
    
    if(period.compositores){

        final_html += `<ul class="no-mark-list w3-margin w3-padding flex-box flex-column space-evenly" style="width:50%">`

        period.compositores.forEach(c => {
            final_html += `
                        <li>
                            <div class="w3-light-blue w3-margin w3-padding w3-card-4 flex-box flex-center">
                                <a class="w3-center" href="/compositores/${c.id}">${c.nome}</a>
                            </div>
                        </li>
            `
        })

        final_html += '</ul>'
    }
        
            
    final_html += `
            </div>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodPage = periodPage

function periodDeletePage(period){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Periodo apagado</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Periodo apagado</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <div class="w3-panel w3-green">
                <h3>Periodo apagado!</h3>
                <p>O periodo ${period.id} foi apagado com sucesso.</p>
            </div>
            <a class="w3-button w3-round w3-blue-grey" href="/periodos">Ok</a>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodDeletePage = periodDeletePage

function periodEditPage(period){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Editar Periodo</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Editar Periodo</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/periodos/edit/${period.id}" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${period.id}"/>
                    <br/>
                    <label>Início</label>
                    <input class="w3-input w3-round" type="text" name="start" value="${period.start}"/>
                    <br/>
                    <label>Fim</label>
                    <input class="w3-input w3-round" type="text" name="end" value="${period.end}"/>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/periodos">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodEditPage = periodEditPage

function periodFailedEditPage(period){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Editar Periodo</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Editar Periodo</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <div class="w3-panel w3-red w3-margin w3-padding">
            <h3>Edição revertida!</h3>
            <p>Não é permitido modificar o identificador do período.</p>
        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/periodos/edit/${period.id}" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${period.id}"/>
                    <br/>
                    <label>Início</label>
                    <input class="w3-input w3-round" type="text" name="start" value="${period.start}"/>
                    <br/>
                    <label>Fim</label>
                    <input class="w3-input w3-round" type="text" name="end" value="${period.end}"/>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/periodos">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodFailedEditPage = periodFailedEditPage

function periodAddPage(){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Adicionar Periodo</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Adicionar Periodo</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/periodos/add" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id"/>
                    <br/>
                    <label>Início</label>
                    <input class="w3-input w3-round" type="text" name="start"/>
                    <br/>
                    <label>Fim</label>
                    <input class="w3-input w3-round" type="text" name="end"/>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/periodos">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodAddPage = periodAddPage

function periodEmptyAddPage(period){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Adicionar Periodo</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Adicionar Periodo</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <div class="w3-panel w3-yellow w3-margin w3-padding">
            <h3>Adição impedida!</h3>
            <p>Nenhum pode permanecer em branco.</p>
        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/periodos/add" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${period.id}"/>
                    <br/>
                    <label>Início</label>
                    <input class="w3-input w3-round" type="text" name="start" value="${period.start}"/>
                    <br/>
                    <label>Fim</label>
                    <input class="w3-input w3-round" type="text" name="end" value="${period.end}"/>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/periodos">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodEmptyAddPage = periodEmptyAddPage

function periodFailedAddIdPage(period){
    let final_html = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Adicionar Periodo</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css">
        <link rel="stylesheet" href="/w3.css">
    </head>

    <body class="w3-light-grey">
        <div class="w3-row flex-box">

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>
                
            <header class="w3-half w3-container w3-blue-grey w3-center">
                <h3>Adicionar Periodo</h3>
            </header>

            <div class="w3-quarter flex-box flex-center w3-blue-grey full-height-div">
            </div>

        </div>

        <div class="w3-panel w3-red w3-margin w3-padding">
            <h3>Adição impedida!</h3>
            <p>O identificador do período precisa ser único.</p>
        </div>

        <main class="w3-margin w3-padding">
            <form method="POST" action="/periodos/add" enctype="application/x-www-form-urlencoded">
                <fieldset>
                    <legend>Dados</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" value="${period.id}"/>
                    <br/>
                    <label>Início</label>
                    <input class="w3-input w3-round" type="text" name="start" value="${period.start}"/>
                    <br/>
                    <label>Fim</label>
                    <input class="w3-input w3-round" type="text" name="end" value="${period.end}"/>
                    <br/>
                </fieldset>
                <div class="w3-margin w3-padding flex-box space-evenly">
                    <a class="w3-button w3-round w3-blue-grey" href="/periodos">Cancelar</a>
                    <button class="w3-button w3-round w3-blue-grey" type="submit">Guardar Alterações</button>
                </div>
            </form>
        </main>

        <footer class="w3-container w3-blue-grey">
            <h5>Generated by CompositoresApp::EngWeb2024::A100695 [<a class="w3-center" href="/">Voltar à página principal</a>]</h5>
        </footer>
    </body>

    </html>
    `

    return final_html
}

exports.periodFailedAddIdPage = periodFailedAddIdPage

