import json, os

dataset = open("emd.json")

data = json.load(dataset)

dataset.close()

for p in data:
    nome = p["nome"]["primeiro"] + " " + p["nome"]["último"]
    day = p["dataEMD"]
    idade = p["idade"]
    genero = p["género"]
    modalidade = p["modalidade"]
    clube = p["clube"]
    resultado = p["resultado"]
    index = p["index"]

    pageHTML = f"""
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Exame Médico Desportivo: {nome}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <title>Document</title>
    </head>

    <body>

        <div class="w3-card-4">

            <header class="w3-container w3-purple">
                <h3>Exame Médico Desportivo: {nome}</h3>
            </header>

            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <td><b>Data do EMD</b></td>
                        <td>{day}</td>
                    </tr>
                    <tr>
                        <td><b>Idade</b></td>
                        <td>{idade}</td>
                    </tr>
                    <tr>
                        <td><b>Género</b></td>
                        <td>{"Feminino" if genero else "Masculino"}</td>
                    </tr>
                    <tr>
                        <td><b>Modalidade</b></td>
                        <td>{modalidade}</td>
                    </tr>
                    <tr>
                        <td><b>Clube</b></td>
                        <td>{clube}</td>
                    </tr>
                    <tr>
                        <td><b>Resultado</b></td>
                        <td><b>{"Apto" if resultado else "Inapto"}</b></td>
                    </tr>
                </table>
            </div>

            <footer class="w3-container w3-purple">
                <h5>Generated by EMDApp::EngWeb2024::A100695</h5>
                <address>
                    <a href="index.html">Voltar à página principal</a>
                </address>
            </footer>

        </div>

    </body>

    </html>
    """

    f = open(f'./emdSite/emd{index}.html', 'w')
    f.write(pageHTML)
    f.close()
