import json

def chaveOrd(r):
    return r["rua"]["meta"]["nome"]

dataset = open("test.json")

data = json.load(dataset)

dataset.close()

data.sort(key = chaveOrd)

preHTML = """
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <title>Ruas da Cidade de Braga</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <title>Document</title>
    </head>

    <body>

        <div class="w3-card-4">

            <header class="w3-container w3-purple">
                <h3>Ruas da Cidade de Braga</h3>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
    """

posHTML = """
                </ul>
            </div>

            <footer class="w3-container w3-purple">
                <h5>Generated by RCBApp::EngWeb2024::A100695</h5>
            </footer>

        </div>

    </body>

    </html>
"""

content = ""

for r in data:
    nome = r["rua"]["meta"]["nome"]
    numero = r["rua"]["meta"]["número"]

    content += f"""
    <li>
         <a href="rua{numero}.html">{nome}</a>
    </li>
    """

pageHTML = preHTML + content + posHTML

f = open('./ruaSite/index.html', 'w')
f.write(pageHTML)
f.close()

print(len(data))
